services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
          - "8081:8081"
        depends_on:
          - localpostgresql
        environment:
          - ConnectionStrings__DefaultConnection=Host=db;Database=pruebaFGRP;Username=postgres;Password=PassProxy$2024
    localpostgresql:
        image: postgres:13-alpine
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=PassProxy$2024
        ports:
            - '3308:5432'
        volumes:
            - ./startup.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
